### PR TITLE
Merge develop into master

### PR DESCRIPTION
**Pull request by yuce**

### CODE REVIEW

**Comment by codysoyland** [comment]
Do you know why the build is failing?

**Comment by yuce** [comment]
@codysoyland I think https://s3.amazonaws.com/build.pilosa.com/pilosa-master-linux-amd64.tar.gz is not up-to-date. The tests fail against that, but they pass when run against `git master`.

**Comment by codysoyland** [comment]
@yuce ah, good find. I did some digging and the binary prereleases are indeed not being uploaded. I put my notes in this ticket: https://github.com/pilosa/pilosa/issues/1497

Will try to resolve this tomorrow.

**Comment by yuce** [comment]
Thanks @cody

**Comment by yuce** [comment]
ping! ping!

**Pull request merged**
