### PR TITLE
Compatibility with Pilosa server/develop

### PR DESCRIPTION
**Pull request by yuce**

### CODE REVIEW

**Comment by codysoyland** [comment]
Hey Yuce, sorry for the delay on this. Are the CI failures due to running against master instead of develop?

**Comment by yuce** [comment]
@codysoyland Yeah, that's right.

**Comment by codysoyland** [comment]
Have you run it against the new pql changes (just merged)? I ran `pilosa server` (with newest `develop` branch) and then `PILOSA_BIND="http://:10101" LEGACY_MODE_OFF=true make test-all` and I'm getting `pilosa.client.PilosaServerError: Server error (406): JSON only acceptable response`.

**Comment by yuce** [comment]
We used to set the `Accept` and `Content-Type` headers to protobuf since most of the handlers didn't care about those. I've removed the defaults and those headers are set only for query and import endpoints. There are missing tests for new PQL calls. I'll fix them and commit.

**Comment by yuce** [comment]
Closing. Fixed in https://github.com/pilosa/pilosa/tree/wip-api-refactor

**Comment by yuce** [comment]
Oops...

**Comment by yuce** [comment]
@codysoyland This branch works with the latest`develop` again.

**Pull request merged**
