### PR TITLE
Added initial tracing support.

### LINKED ISSUE #141: Add tracing support

### PR DESCRIPTION
**Pull request by yuce**
Fixes #141

### CODE REVIEW

**Comment by alanbernstein** [comment]
I'm trying to run the example script, but I'm getting an odd error:

```
$ python tracing-test.py
Traceback (most recent call last):
  File "tracing-test.py", line 42, in <module>
    main()
  File "tracing-test.py", line 29, in main
    schema = client.schema()
  File "/Users/abernstein/src/pilosa/python-pilosa/pilosa/client.py", line 280, in schema
    with self.tracer.scope_manager.activate(span, True) as scope:
AttributeError: 'Tracer' object has no attribute 'scope_manager'
```

Some version info:
```
$ pip install jaeger-client
Requirement already satisfied: jaeger-client in /usr/local/lib/python3.7/site-packages (3.13.0)
Requirement already satisfied: thrift in /usr/local/lib/python3.7/site-packages (from jaeger-client) (0.11.0)
Requirement already satisfied: tornado<5,>=4.3 in /usr/local/lib/python3.7/site-packages (from jaeger-client) (4.5.3)
Requirement already satisfied: opentracing<2,>=1.2.2 in /usr/local/lib/python3.7/site-packages (from jaeger-client) (1.3.0)
Requirement already satisfied: threadloop<2,>=1 in /usr/local/lib/python3.7/site-packages (from jaeger-client) (1.0.2)
Requirement already satisfied: six>=1.7.2 in /usr/local/lib/python3.7/site-packages (from thrift->jaeger-client) (1.11.0)
```

I wonder if there is a better way for me to use this branch of the pilosa client while using the test script?

**Comment by yuce** [comment]
It seems jaeger client is not compatible with OpenTracing 2, I've downgraded it to1.3.0

**Comment by alanbernstein** [comment]
With this change, the script finishes, but in the Jaeger UI, I only see `jaeger-query` in the service dropdown

**Comment by yuce** [comment]
Great!

**Pull request merged**
