### PR TITLE
Implements the Store call

### LINKED ISSUE #126: Implement Store call

### PR DESCRIPTION
**Pull request by yuce**
Fixes #126 
~Requires Pilosa built from https://github.com/pilosa/pilosa/pull/1666~

### CODE REVIEW

**Comment by yuce** [comment]
Since `Store` PR was merged to Pilosa master, this PR can be merged.

**Comment by yuce** [comment]
ping!

**Comment by alanbernstein** [comment]
This looks good, but I'm having trouble passing tests.

`Pilosa v1.1.0-176-gf62dbc00, build time 2018-10-11T15:07:15+0000`, starting with an empty data directory

`make test-all` -> `3 failed, 137 passed in 5.55 seconds`

The following three all fail in similar ways:
ClientIT.test_csv_import_time_field
ClientIT.test_not_
ClientIT.test_store

trimmed output form `test_store`:
```
self = <pilosa.client.Client object at 0x10543ecd0>, method = 'POST', path = '/index/testidx-30/field/exists'
data = '{"options": {"timeQuantum": "", "type": "time"}}', headers = None, use_coordinator = False
...
E       PilosaServerError: Server error (500): {"success":false,"error":{"message":"reserved index or field name"}}

pilosa/client.py:367: PilosaServerError
```

Am I doing something wrong here?

I got tests to pass by skipping `if field_name == 'exists'` in the first field loop of `sync_schema`, but it's not clear why I'm seeing errors here if you're not.

**Comment by yuce** [comment]
Found the issue, pushing a fix in a few.

**Comment by yuce** [comment]
Thanks for noticing that problem, I've pushed a fix.

**Pull request merged**
